[package]
name = "gpxwrench"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
time = { version = "0", features = ["parsing"] }
quick-xml = "0"

[dev-dependencies]
gpx = "0"
assert_cmd = "2"
predicates = "3"
